# Generated by Django 5.1 on 2026-04-16 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(max_length=20)),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Створено'), ('accepted', 'Прийнято'), ('in_transit', 'У дорозі'), ('arrived', 'Прибула'), ('delivered', 'Доставлено'), ('returned', 'Повернуто')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Створено'), ('accepted', 'Прийнято'), ('in_transit', 'У дорозі'), ('arrived', 'Прибула'), ('delivered', 'Доставлено'), ('returned', 'Повернуто')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='tracking.parcel')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='tracking.postoffice')),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='destination_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_parcels', to='tracking.postoffice'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='origin_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_parcels', to='tracking.postoffice'),
        ),
    ]
