# Generated by Django 5.1 on 2026-04-16 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='declared_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status'], name='tracking_pa_status_0b4954_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['created_at'], name='tracking_pa_created_8aab23_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status', 'created_at'], name='tracking_pa_status_45d9fb_idx'),
        ),
    ]
